version: "3.9"

services:
  openstrm:
    build: .
    image: wabisabi926/openstrm:latest
    container_name: openstrm
    ports:
      - "3000:3000"
      - "8091:8091"
    environment:
      - NODE_ENV=production
    volumes:
      - ./strmData:/app/data
      - ./config:/app/config
      - ./emby2Alist/nginx/log:/var/log/nginx
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 256M
